/*
 * Copyright(c) 2016 - Present, Clouds Studio Holding Limited. All rights reserved.
 * Project : scrm
 * File : ScrmVisitPlanRepository.java
 * Date : 2026/08/05 08:55:12
 * Author : Hsi Chu
 * Contact : hiylo@live.com
 */
package org.hiylo.scrm.repository;

import org.hiylo.scrm.entity.ScrmVisitPlanEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

/**
 * SCRM 客户回访计划数据访问层。
 * <p>
 * 供 {@code ScrmVisitService} 计划管理与任务生成使用。
 * </p>
 *
 * @since V1.0
 * @author Hsi Chu
 */
public interface ScrmVisitPlanRepository extends JpaRepository<ScrmVisitPlanEntity, Long>,
        JpaSpecificationExecutor<ScrmVisitPlanEntity> {

    /**
     * 按计划编码查询 (数据隔离)。
     *
     * @param planCode 计划编码
     * @return 计划实体 (不存在返回 empty)
     */
    Optional<ScrmVisitPlanEntity> findByPlanCode(String planCode);

    /**
     * 查询需要自动生成任务的计划 (启用自动生成, 状态为 ACTIVE, 且下次生成时间已到)。
     *
     * @param now      当前时间
     * @return 计划列表
     */
    @Query(value = "SELECT p FROM ScrmVisitPlanEntity p WHERE p.autoGenerate = TRUE AND p.status = 'ACTIVE' AND "
                          + "p.nextGenerateAt IS NOT NULL AND p.nextGenerateAt <= :now")
    List<ScrmVisitPlanEntity> findAutoGenerateDue(
                                                  @Param("now") java.time.LocalDateTime now);
}
